[2022-01-13 16:01:03,863] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: query_raw_table_to_s3.run_this manual__2022-01-13T16:01:02.978663+00:00 [queued]>
[2022-01-13 16:01:03,875] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: query_raw_table_to_s3.run_this manual__2022-01-13T16:01:02.978663+00:00 [queued]>
[2022-01-13 16:01:03,876] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-01-13 16:01:03,877] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-01-13 16:01:03,878] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-01-13 16:01:03,891] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): run_this> on 2022-01-13 16:01:02.978663+00:00
[2022-01-13 16:01:03,898] {standard_task_runner.py:52} INFO - Started process 422 to run task
[2022-01-13 16:01:03,903] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'query_raw_table_to_s3', 'run_this', 'manual__2022-01-13T16:01:02.978663+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/cape_job_raw_to_flat_attr_s3.py', '--cfg-path', '/tmp/tmp7dk5graw', '--error-file', '/tmp/tmpnc_21t_6']
[2022-01-13 16:01:03,904] {standard_task_runner.py:77} INFO - Job 8: Subtask run_this
[2022-01-13 16:01:03,985] {logging_mixin.py:109} INFO - Running <TaskInstance: query_raw_table_to_s3.run_this manual__2022-01-13T16:01:02.978663+00:00 [running]> on host b05296965021
[2022-01-13 16:01:04,051] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=douglastome@capeanalytics.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=query_raw_table_to_s3
AIRFLOW_CTX_TASK_ID=run_this
AIRFLOW_CTX_EXECUTION_DATE=2022-01-13T16:01:02.978663+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-01-13T16:01:02.978663+00:00
[2022-01-13 16:01:04,054] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-13 16:01:04,055] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-13 16:01:04,056] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-13 16:01:04,057] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'next_execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_end' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-13 16:01:04,059] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-13 16:01:04,060] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-13 16:01:04,062] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-13 16:01:04,063] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'prev_execution_date_success' from the template is deprecated and will be removed in a future version. Please use 'prev_data_interval_start_success' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-13 16:01:04,063] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-13 16:01:04,064] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'tomorrow_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-13 16:01:04,065] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-13 16:01:04,066] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'yesterday_ds_nodash' from the template is deprecated and will be removed in a future version.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-01-13 16:01:04,067] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/cape_job_raw_to_flat_attr_s3.py", line 168, in run_this_func
    format(kwargs['dag_run'].conf['message']))
KeyError: 'message'
[2022-01-13 16:01:04,084] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=query_raw_table_to_s3, task_id=run_this, execution_date=20220113T160102, start_date=20220113T160103, end_date=20220113T160104
[2022-01-13 16:01:04,100] {standard_task_runner.py:92} ERROR - Failed to execute job 8 for task run_this
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/cape_job_raw_to_flat_attr_s3.py", line 168, in run_this_func
    format(kwargs['dag_run'].conf['message']))
KeyError: 'message'
[2022-01-13 16:01:04,118] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-01-13 16:01:04,157] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
